version: '3.6'
services:

  nginx-front:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx-front.conf:/etc/nginx/nginx.conf
    links:
      - front
      - back

  front:
    image: node:10
    command: ["/bin/sh", "-c","cd /home/app && npm run start"]
    ports:
      - "3001:3000"
    environment:
      REACT_EDITOR: atom
      PGUSER: ${PG_USER}
      PGPASSWORD: ${PG_PASSWORD}
      PGDATABASE: ${PG_DATABASE}
      PGHOST: postgres
    volumes:
     - ./front:/home/app

  back:
    image: node:10
    command: ["/bin/sh", "-c","cd /home/app && npm run dev"]
    volumes:
     - ./back:/home/app
    environment:
      PGUSER: ${PG_USER}
      PGPASSWORD: ${PG_PASSWORD}
      PGDATABASE: ${PG_DATABASE}
      PGHOST: postgres
    links:
      - postgres


  postgres:
    image: postgres:9.6.18
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
      - ./db:/init

  pgweb:
    image: sosedoff/pgweb
    command: pgweb --readonly --bind=0.0.0.0 --listen=5081
    ports: ["5000:5081"]
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}?sslmode=disable
    depends_on:
      - postgres

  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: hasura
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey    
  
volumes:
  data: {}
